default:
  site:
    review_period: '13 months'
    spaces:
      - space_path: client-php
        space_name: PHP Client SDK
    branch: 'main'
    dev_browser_path: client-php
development:
  isDev: true
